version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe_app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=recipe_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: recipe_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recipe_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
